### ISSUE TITLE
ng-super is not generating files. 

### ISSUE THREAD

**Issue by mir-nawaz-10p** [mohuk/generator-ng-super#26]
Here are the details and screenshots. 

```
abc@dev-abc:~/mbo/connect-webapp$ yo ng-super:factory associate.test
module.js:338
    throw err;
          ^
Error: Cannot find module 'duplexify'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/mirnawaz/.nvm/versions/node/v0.12.3/lib/node_modules/yo/node_modules/update-notifier/node_modules/latest-version/node_modules/package-json/node_modules/got/index.js:10:17)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

![ng-super-error](https://cloud.githubusercontent.com/assets/12623318/11362909/6cdbc830-92b8-11e5-8c20-cdd24d548e7d.png)

**Comment by umayr** [comment]
Its more likely an issue with `npm 3x`. Majority of packages out there are not compatible with newer version of npm yet. Can you try it with `npm 2x`?

**Comment by mir-nawaz-10p** [comment]
Not solved :( 
node version . 0.12.3
![ng-super-error-2](https://cloud.githubusercontent.com/assets/12623318/11364364/d42bc2ac-92c1-11e5-805f-78259e9bfc34.png)

**Comment by umayr** [comment]
Okay, one last thing, what version of generator you're using?

**Comment by mir-nawaz-10p** [comment]
its the latest version .
Installed today . 
npm install -g generator-ng-super

ng-super@0.0.8

**Comment by mir-nawaz-10p** [comment]
after reverting npm version to 2. 
I uninstalled ng-super 
and reinstalled it. 
it started working. 
:+1:
